### ISSUE TITLE
齊藤京子的message不能backup

### ISSUE THREAD

**Issue by dickson870** [easonyen16/b4nd-crawler#1]
先感謝作者寫此爬蟲

我是用account login方式backup 當login後爬蟲程式顯示APP版本更新不能使用(我是第一次使用此程式)

是否有什麼出錯?

**Comment by dickson870** [comment]
補充:我是用version 1.3.1

**Comment by dickson870** [comment]
再update:我轉用token id 可備份了
再次感謝作者

**Comment by easonyen16** [comment]
Fixed in 1.3.2.
[https://github.com/easonyen16/b4nd-crawler/releases/tag/v1.3.2](https://github.com/easonyen16/b4nd-crawler/releases/tag/v1.3.2)

**Comment by dickson870** [comment]
感謝作者瞬速修正 

希望新的京子message app你都會寫爬蟲backup

再次感謝

**Comment by easonyen16** [comment]
因為沒有訂閱，所以暫時沒有寫的計劃
